(function(root){
'use strict';
const W=9,H=7, KEY='pig-land-gahyun-v1';
const buildings={road:{name:'농장 길',icon:'🪨',cost:30,desc:'입구와 시설 연결'},pen:{name:'돼지 우리',icon:'🏡',cost:650,desc:'돼지 6마리의 집'},silo:{name:'사료 창고',icon:'🌾',cost:450,desc:'사료 저장 +150'},wash:{name:'소독 시설',icon:'🚿',cost:550,desc:'방역 점수 +20'},clinic:{name:'동물 진료소',icon:'🏥',cost:1000,desc:'치료 · 방역 +15'},quarantine:{name:'격리 우리',icon:'⛺',cost:700,desc:'전파와 악화 감소'},orchard:{name:'감귤 과수원',icon:'🍊',cost:800,desc:'하루 수입 +45'},park:{name:'토토의 정원',icon:'🌳',cost:400,desc:'위생 유지 · 방역 +5'}};
const at=(x,y)=>y*W+x;
function fresh(){let s={version:1,day:1,money:4200,food:120,hygiene:90,tiles:Array(W*H).fill(null),pigs:[],expanded:false,logs:[],sold:0,earned:0,lastNet:0,patrolUntil:0,boostUntil:0,lastPat:0,grants:0,rewards:[],weather:'☀️ 맑음',seed:Math.floor(Math.random()*2147483646)+1};for(let x=2;x<=6;x++)s.tiles[at(x,3)]={type:'road',level:1};for(let y=4;y<=6;y++)s.tiles[at(4,y)]={type:'road',level:1};s.tiles[at(2,2)]={type:'pen',level:1};s.tiles[at(6,2)]={type:'silo',level:1};[2,4,6,6].forEach((age,i)=>s.pigs.push({id:i+1,home:at(2,2),age,health:95,sick:false}));s.nextId=5;log(s,'가현이의 첫 농장에 돼지 4마리가 도착했어요.');log(s,'토토가 농장 입구를 지키기 시작했어요.');return s;}
function log(s,t){s.logs.unshift({day:s.day,text:t});s.logs=s.logs.slice(0,60);}
function rng(s){s.seed=(s.seed*16807)%2147483647;return(s.seed-1)/2147483646;}
function unlocked(s,i){let x=i%W,y=Math.floor(i/W);return s.expanded||(x>=1&&x<=7&&y>=1&&y<=5)||i===at(4,6);}
function adjacent(i){let x=i%W,y=Math.floor(i/W);return [[x-1,y],[x+1,y],[x,y-1],[x,y+1]].filter(([a,b])=>a>=0&&a<W&&b>=0&&b<H).map(([a,b])=>at(a,b));}
function network(s){let seen=new Set(),q=[at(4,6)];while(q.length){let i=q.pop();if(seen.has(i)||s.tiles[i]?.type!=='road')continue;seen.add(i);q.push(...adjacent(i));}return seen;}
function connected(s,i,net=network(s)){return s.tiles[i]?.type==='road'?net.has(i):adjacent(i).some(j=>net.has(j));}
function stats(s){let net=network(s),n={};s.tiles.forEach((t,i)=>{if(t&&connected(s,i,net))n[t.type]=(n[t.type]||0)+t.level;});let capacity=6*(n.pen||0),health=s.pigs.length?Math.round(s.pigs.reduce((a,p)=>a+p.health,0)/s.pigs.length):100;let protection=Math.min(98,Math.round(15+s.hygiene*.35+Math.min(40,(n.wash||0)*20)+Math.min(30,(n.clinic||0)*15)+Math.min(10,(n.park||0)*5)+(s.patrolUntil>=s.day?15:0)+(s.boostUntil>=s.day?20:0)));return{n,net,capacity,health,protection,foodMax:200+(n.silo||0)*150,sick:s.pigs.filter(p=>p.sick).length,ready:s.pigs.filter(p=>p.age>=8&&p.health>=65&&!p.sick&&connected(s,p.home,net)),upkeep:Object.entries(n).reduce((a,[k,v])=>a+(['pen','clinic','wash','quarantine'].includes(k)?v*({pen:8,clinic:14,wash:6,quarantine:8}[k]):0),0)};}
function spend(s,c){if(s.money<c)return false;s.money-=c;return true;}
function build(s,i,type){if(!Number.isInteger(i)||i<0||i>=W*H||!buildings[type])return'올바른 땅과 시설을 골라 주세요.';if(!unlocked(s,i))return'먼저 땅을 넓혀 주세요.';if(s.tiles[i])return'이미 시설이 있는 자리예요.';if(!spend(s,buildings[type].cost))return'운영 자금이 부족해요.';s.tiles[i]={type,level:1};log(s,`${buildings[type].name} 건설 완료!${connected(s,i)?'':' 입구로 이어지는 길을 붙여 주세요.'}`);checkGoals(s);return null;}
function upgrade(s,i){let t=s.tiles[i];if(!t||t.type==='road')return'시설을 선택해 주세요.';if(t.level>=3)return'이미 최고 레벨이에요.';let price=Math.round(buildings[t.type].cost*.7*t.level);if(!spend(s,price))return'운영 자금이 부족해요.';t.level++;log(s,`${buildings[t.type].name} ${t.level}단계로 증축했어요.`);checkGoals(s);return null;}
function demolish(s,i){if(i===at(4,6))return'농장 입구는 철거할 수 없어요.';let t=s.tiles[i];if(!t)return'시설을 선택해 주세요.';if(s.pigs.some(p=>p.home===i))return'돼지가 살고 있어요. 모두 출하한 뒤 철거해 주세요.';s.money+=Math.floor(buildings[t.type].cost*.4);s.tiles[i]=null;let st=stats(s);s.food=Math.min(s.food,st.foodMax);log(s,`${buildings[t.type].name} 철거. 최초 건설비의 40%를 돌려받았어요.`);return null;}
function action(s,kind){let st=stats(s);
if(kind==='buy'){let home=s.tiles.findIndex((t,i)=>t?.type==='pen'&&connected(s,i,st.net)&&s.pigs.filter(p=>p.home===i).length<6*t.level);if(home<0)return'길과 연결된 우리에 빈자리가 없어요.';if(!spend(s,90))return'아기 돼지를 맞이하려면 90코인이 필요해요.';s.pigs.push({id:s.nextId++,home,age:0,health:100,sick:false});log(s,'아기 돼지 한 마리가 새 식구가 됐어요.');}
else if(kind==='feed'){let amount=Math.min(80,Math.floor(st.foodMax-s.food));if(amount<=0)return'사료 창고가 가득 찼어요.';if(!spend(s,amount*2))return'사료를 살 자금이 부족해요.';s.food+=amount;log(s,`사료 ${amount}kg을 채웠어요. 매일 자동으로 급여해요.`);}
else if(kind==='sell'){if(!st.ready.length)return'생후 8일 · 건강 65 이상인 건강한 돼지를 기다려 주세요. 길 연결도 필요해요.';let ids=new Set(st.ready.map(p=>p.id)),cash=st.ready.reduce((a,p)=>a+Math.round(260+p.health*.7),0);s.pigs=s.pigs.filter(p=>!ids.has(p.id));s.money+=cash;s.earned+=cash;s.sold+=ids.size;log(s,`건강한 돼지 ${ids.size}마리 출하! +${cash.toLocaleString()}코인`);}
else if(kind==='clean'){if(s.hygiene>=100)return'농장이 이미 깨끗해요.';if(!spend(s,80))return'청소 비용 80코인이 필요해요.';s.hygiene=Math.min(100,s.hygiene+35);log(s,'구석구석 청소했어요. 위생 +35!');}
else if(kind==='patrol'){if(s.patrolUntil>=s.day)return'토토가 아직 순찰 중이에요.';s.patrolUntil=s.day+2;log(s,'토토 출동! 오늘부터 3일 동안 방역 +15.');}
else if(kind==='boost'){if(s.boostUntil>=s.day)return'집중 방역이 아직 적용 중이에요.';if(!spend(s,150))return'방역 비용 150코인이 필요해요.';s.boostUntil=s.day+3;log(s,'4일간 집중 방역을 시작했어요. 방역 +20.');}
else if(kind==='treat'){if(!st.sick)return'모두 건강해요. 치료할 돼지가 없어요.';let price=st.sick*(st.n.clinic?35:65);if(!spend(s,price))return`치료 비용 ${price}코인이 필요해요.`;s.pigs.forEach(p=>{if(p.sick){p.sick=false;p.health=Math.min(100,p.health+40);}});log(s,`수의사의 돌봄으로 ${st.sick}마리가 회복했어요.`);}
else if(kind==='expand'){if(s.expanded)return'농장 부지를 모두 확보했어요.';if(!spend(s,1800))return'부지 확장에 1,800코인이 필요해요.';s.expanded=true;log(s,'바다가 보이는 새 부지! 농장을 더 넓게 설계할 수 있어요.');}
else if(kind==='grant'){if(s.money>=180)return'자금이 180코인 미만일 때 지원을 받을 수 있어요.';if(s.grants>=3)return'세 번의 응원금을 모두 사용했어요. 출하나 과수원 수입을 기다리거나 새 농장을 시작해 보세요.';s.money+=700;s.grants++;log(s,'아빠의 응원금 +700코인. 다시 시작할 수 있어!');}
else return'알 수 없는 행동이에요.';
checkGoals(s);return null;}
function goals(s){let st=stats(s);let pens=s.tiles.filter(t=>t?.type==='pen').length;return[{id:'first',title:'첫 출하의 설렘',desc:'건강한 돼지 4마리를 출하해 보세요.',value:s.sold,target:4,reward:500},{id:'design',title:'설계자의 손길',desc:'돼지 우리 3동으로 농장을 넓혀 보세요.',value:pens,target:3,reward:700},{id:'safe',title:'토토의 안심 농장',desc:'방역 점수 80을 달성해 보세요.',value:st.protection,target:80,reward:600},{id:'dream',title:'가현이의 제주 드림',desc:'누적 20마리 출하. 우리의 꿈이 자라나요.',value:s.sold,target:20,reward:2000}];}
function checkGoals(s){for(const g of goals(s)){if(g.value>=g.target&&!s.rewards.includes(g.id)){s.rewards.push(g.id);s.money+=g.reward;log(s,`🏅 ${g.title} 달성! 보상 +${g.reward}코인`);}}}
function step(s){let before=s.money;s.day++;let st=stats(s);let weatherRoll=rng(s);s.weather=weatherRoll<.18?'🌧️ 비':weatherRoll<.38?'🌬️ 바람':'☀️ 맑음';let need=s.pigs.length,ratio=need?Math.min(1,s.food/need):1;s.food=Math.max(0,s.food-need);s.hygiene=Math.max(0,Math.min(100,s.hygiene-3-s.pigs.length*.18+(st.n.park||0)*1.6-(s.weather==='🌧️ 비'?2:0)));st=stats(s);let exposure=rng(s)<.2+(s.weather==='🌧️ 비'?.08:0),sickBefore=st.sick,infected=0,lost=0;
s.pigs=s.pigs.filter(p=>{let linked=connected(s,p.home,st.net);if(ratio>=1&&linked&&!p.sick)p.age++;p.health+=ratio>=1?(linked?1:-4):-10;if(!p.sick&&(exposure||sickBefore)&&rng(s)<(1-st.protection/100)*(sickBefore?(st.n.quarantine?.08:.25):.3)){p.sick=true;infected++;}if(p.sick){p.health-=st.n.quarantine?5:10;if(st.n.clinic){p.health+=Math.min(12,st.n.clinic*4);if(rng(s)<.25){p.sick=false;p.health+=15;}}}if(s.hygiene<25)p.health-=3;p.health=Math.max(0,Math.min(100,p.health));if(p.health===0){lost++;return false;}return true;});
let cost=Math.min(s.money,st.upkeep);s.money-=cost;if(cost<st.upkeep)log(s,'유지비가 부족해요. 출하 또는 응원금으로 자금을 마련해 주세요.');let harvest=(st.n.orchard||0)*(s.weather==='🌧️ 비'?35:45);s.money+=harvest;s.earned+=harvest;
if(infected)log(s,`⚠️ 전염병 발생: ${infected}마리가 아파요. 돌보기에서 치료해 주세요.`);if(lost)log(s,`아픈 돼지 ${lost}마리를 잃었어요. 남은 돼지들의 건강을 살펴 주세요.`);if(ratio<1&&need)log(s,'사료가 부족해 성장이 멈추고 건강이 떨어졌어요.');if(exposure&&!infected&&need)log(s,'🛡️ 외부 감염 위험을 잘 넘겼어요.');if(s.day%3===0&&!infected&&ratio===1)log(s,harvest?`감귤 과수원에서 ${harvest}코인의 수입이 생겼어요.`:'제주 바람을 맞으며 돼지들이 쑥쑥 자라요.');checkGoals(s);s.lastNet=s.money-before;return s;}
function valid(s){return s&&s.version===1&&Number.isInteger(s.day)&&s.day>0&&Number.isFinite(s.money)&&s.money>=0&&Number.isFinite(s.food)&&s.food>=0&&Number.isFinite(s.hygiene)&&Array.isArray(s.tiles)&&s.tiles.length===63&&s.tiles.every(t=>t===null||(buildings[t.type]&&Number.isInteger(t.level)&&t.level>=1&&t.level<=3))&&Array.isArray(s.pigs)&&s.pigs.every(p=>Number.isFinite(p.health)&&Number.isFinite(p.age)&&s.tiles[p.home]?.type==='pen')&&Array.isArray(s.logs)&&Array.isArray(s.rewards)&&Number.isFinite(s.seed)&&Number.isFinite(s.nextId);}
const api={W,H,KEY,buildings,at,fresh,log,unlocked,adjacent,network,connected,stats,build,upgrade,demolish,action,goals,step,valid};if(typeof module!=='undefined')module.exports=api;else root.Farm=api;
})(typeof window!=='undefined'?window:globalThis);
