'use strict';
const F=window.Farm,$=id=>document.getElementById(id),fmt=n=>Math.round(n).toLocaleString('ko-KR');
let state=F.fresh(),loadIssue=false;try{let raw=localStorage.getItem(F.KEY);if(raw){let saved=JSON.parse(raw);if(F.valid(saved))state=saved;else loadIssue=true;}}catch{loadIssue=true;}
let tab='build',mode='pen',selected=null,playing=false,speed=1,timer=null,toastTimer=null;
function toast(t){$('toast').textContent=t;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3800);}
function save(){try{localStorage.setItem(state.league?League.key(state.league.player):F.KEY,JSON.stringify(state));$('save-status').textContent='자동 저장됨';}catch{$('save-status').textContent='저장 불가 · 창을 닫으면 초기화';}}
function run(fn){let oldRewards=state.rewards.length;let err=fn();if(err)toast(err);else{save();if(state.rewards.length>oldRewards)toast('🏅 목표 달성! 보상금을 받았어요.');}render();}
function render(){let st=F.stats(state);$('day').textContent=`${state.day}일째`;$('weather').textContent=state.weather;$('season').textContent=['제주의 봄','제주의 여름','제주의 가을','제주의 겨울'][Math.floor((state.day-1)/30)%4];$('money').textContent=fmt(state.money);$('income').textContent=`지난 하루 ${state.lastNet>=0?'+':''}${fmt(state.lastNet)} · 유지비 ${st.upkeep}/일`;$('pigs').textContent=`${state.pigs.length}마리`;$('capacity').textContent=`정원 ${st.capacity} · 출하 가능 ${st.ready.length}`;$('food').textContent=`${fmt(state.food)} kg`;$('food-days').textContent=state.pigs.length?`약 ${Math.floor(state.food/state.pigs.length)}일분 · 매일 자동 급여`:'새 식구를 기다리는 사료';$('health').textContent=`${st.health}%`;$('security').textContent=`방역 ${st.protection} · ${st.sick?`치료 필요 ${st.sick}마리`:'모두 건강해요'}`;$('health').style.color=st.sick?'#af543b':'';$('expand').disabled=state.expanded;$('expand').innerHTML=state.expanded?'확장 완료 ✓':'땅 넓히기 ↗ <b>1,800</b>';$('land-count').textContent=state.expanded?'63칸':'36칸';$('map-hint').textContent=tab==='build'?`${F.buildings[mode].name} 선택 중 · 빈 땅을 눌러 건설`:'시설을 누르면 상태를 볼 수 있어요.';
let hint=st.sick?'아픈 돼지가 있어. 돌보기에서 치료를 먼저 하자!':state.food<state.pigs.length*3?'사료가 얼마 안 남았어. 창고부터 채워 줄까?':st.ready.length?`${st.ready.length}마리가 잘 자랐어! 출하하고 새 식구를 맞이하자.`:state.hygiene<50?'토토가 청소가 필요하대. 깨끗한 농장이 건강한 농장이야.':state.pigs.length===0?'우리 안이 조용하네. 아기 돼지를 맞이해 보자!':'길 옆에 우리를 짓고, 우리만의 농장을 넓혀 보자.';$('advice').textContent=hint;$('toto-message').textContent=state.patrolUntil>=state.day?`순찰 중! 방역 +15 · ${state.patrolUntil-state.day+1}일 남음`:'멍! 돌보기에서 순찰을 보내 줘.';
renderMap(st);renderPanel(st);$('journal').replaceChildren(...state.logs.slice(0,12).map(l=>{let li=document.createElement('li'),time=document.createElement('time'),text=document.createElement('span');time.textContent=`${l.day}일`;text.textContent=l.text;li.append(time,text);return li;}));let g=F.goals(state).find(g=>!state.rewards.includes(g.id));if(g){$('goal-title').textContent=g.title;$('goal-desc').textContent=g.desc;$('goal-progress').style.width=`${Math.min(100,g.value/g.target*100)}%`;$('goal-count').textContent=`${Math.min(g.value,g.target)} / ${g.target} · 보상 ${fmt(g.reward)}코인`;}else{$('goal-title').textContent='우리의 제주 드림, 완성!';$('goal-desc').textContent='가현아, 네가 만들어 갈 모든 날을 응원해. 농장은 계속 자라요.';$('goal-progress').style.width='100%';$('goal-count').textContent='🏆 모든 목표 달성 · 자유롭게 계속 플레이';}}
function renderMap(st){let frag=document.createDocumentFragment();state.tiles.forEach((t,i)=>{let b=document.createElement('button'),open=F.unlocked(state,i),x=i%9,y=Math.floor(i/9),isGate=i===F.at(4,6);b.className=`tile ${!open?'locked':t?(t.type==='road'?'road':'built'):'empty'} ${selected===i?'selected':''}`;let name=t?F.buildings[t.type].name:open?'빈 땅':'미확장 부지';b.setAttribute('aria-label',`${x+1}열 ${y+1}행 ${name}${t?' '+t.level+'단계':''}`);let residents=state.pigs.filter(p=>p.home===i),bad=residents.some(p=>p.sick),icon=!open?((i%4===0)?'🌲':'🌿'):isGate?'🚪':t?F.buildings[t.type].icon:(i%11===0?'🌼':'');b.innerHTML=`<span class="emoji">${icon}</span>${t&&t.type!=='road'?`<span class="tile-text">${t.type==='pen'?`🐷 ${residents.length}/${t.level*6}`:F.buildings[t.type].name}</span><span class="level">${t.level}</span>`:''}${isGate?'<span class="tile-text">농장 입구</span>':''}${t&&!F.connected(state,i,st.net)?'<span class="warning" title="길 연결 필요">🔗</span>':bad?'<span class="warning">❗</span>':''}`;b.onclick=()=>{if(!open){toast('땅 넓히기를 누르면 이곳에도 건설할 수 있어요.');return;}if(t){selected=i;tab='build';syncTabs();render();return;}if(tab!=='build'){toast('건설 탭에서 시설을 먼저 골라 주세요.');return;}run(()=>F.build(state,i,mode));if(state.tiles[i]){selected=i;render();}};frag.append(b);});$('map').replaceChildren(frag);}
function actionButton(id,title,desc,cost,disabled=false){return `<button class="action" data-action="${id}" ${disabled?'disabled':''}><span><b>${title}</b><small>${desc}</small></span><em>${cost}</em></button>`;}
function renderPanel(st){let p=$('panel');if(tab==='build'){p.innerHTML='<p class="panel-intro">시설 선택 → 빈 땅 클릭. 모든 시설은 입구와 이어진 길 옆에 지어 주세요.</p><div class="build-list">'+Object.entries(F.buildings).map(([k,b])=>`<button class="build-item ${mode===k?'active':''}" data-build="${k}" aria-pressed="${mode===k}"><span>${b.icon}</span><b>${b.name}</b><small>${b.desc}</small><em>🪙 ${fmt(b.cost)}</em></button>`).join('')+'</div>';let t=state.tiles[selected];if(t){let live=F.connected(state,selected,st.net),res=state.pigs.filter(p=>p.home===selected);let info=document.createElement('div');info.className='selected-info';info.innerHTML=`<b>${F.buildings[t.type].icon} ${F.buildings[t.type].name} · ${t.level}단계</b><p>${live?'입구와 연결됨 ✓':'🔗 입구까지 길을 연결해야 시설이 작동해요.'}${t.type==='pen'?`<br>돼지 ${res.length}마리 · 평균 성장 ${res.length?(res.reduce((a,p)=>a+Math.min(8,p.age),0)/res.length).toFixed(1):0}/8일`:''}</p>${t.type!=='road'?`<button id="upgrade" ${t.level>=3?'disabled':''}>${t.level>=3?'최고 단계':'증축 · '+fmt(Math.round(F.buildings[t.type].cost*.7*t.level))}</button>`:''}<button id="demolish">철거</button>`;p.append(info);$('upgrade')?.addEventListener('click',()=>run(()=>F.upgrade(state,selected)));$('demolish').onclick=()=>{let i=selected;openModal(`<h2>시설을 철거할까요?</h2><p>${F.buildings[t.type].name}의 최초 건설비 중 40%를 돌려받아요. 연결된 시설의 길이 끊길 수 있어요.</p><button id="confirm-demolish" class="primary">철거하기</button>`);$('confirm-demolish').onclick=()=>{$('modal').close();run(()=>F.demolish(state,i));};};}p.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{mode=b.dataset.build;selected=null;render();});}
else if(tab==='care'){p.innerHTML=`<div class="stat-line"><span>농장 위생</span><b>${Math.round(state.hygiene)} / 100</b></div><div class="meter"><i style="width:${state.hygiene}%"></i></div>`+actionButton('buy','🐷 아기 돼지 맞이하기','연결된 우리에 한 마리 입주','90')+actionButton('feed','🌾 사료 채우기','최대 80kg · kg당 2코인',fmt(Math.min(80,Math.floor(st.foodMax-state.food))*2))+actionButton('sell',`🚚 건강한 돼지 출하 (${st.ready.length})`,'성장 8일 · 건강 65 이상','수입',!st.ready.length)+actionButton('clean','🧹 농장 청소','위생 +35','80',state.hygiene>=100)+actionButton('patrol','🦮 토토 순찰 보내기','3일 동안 방역 +15','무료',state.patrolUntil>=state.day)+actionButton('boost','🛡️ 집중 방역','4일 동안 방역 +20','150',state.boostUntil>=state.day)+actionButton('treat',`🩺 아픈 돼지 치료 (${st.sick})`,'진료소가 있으면 치료비 할인',fmt(st.sick*(st.n.clinic?35:65)),!st.sick)+(state.money<180?actionButton('grant','💌 아빠의 응원금',`최대 3회 · ${state.grants}/3회 사용`,'+700',state.grants>=3):'');p.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>run(()=>F.action(state,b.dataset.action)));}
else{p.innerHTML='<p class="panel-intro">목표를 달성하면 보상금이 자동으로 들어와요.</p>'+F.goals(state).map(g=>`<div class="goal-row"><b>${state.rewards.includes(g.id)?'🏅':'○'} ${g.title}</b><small>${g.desc}</small><div class="meter"><i style="width:${Math.min(100,g.value/g.target*100)}%"></i></div><small>${state.rewards.includes(g.id)?'달성 완료':`${Math.min(g.value,g.target)} / ${g.target}`} · 보상 ${fmt(g.reward)}</small></div>`).join('');}}
function syncTabs(){document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',tab===b.dataset.tab);b.setAttribute('aria-pressed',tab===b.dataset.tab);});}
function setPlay(on){playing=on;clearInterval(timer);$('play').textContent=on?'Ⅱ':'▶';$('play').setAttribute('aria-label',on?'자동 진행 일시 정지':'자동 진행 시작');$('time-state').textContent=on?'농장이 자라는 중':'잠시 쉬는 중';if(on)timer=setInterval(()=>run(()=>{F.step(state);}),6500/speed);}
function openModal(html){setPlay(false);$('modal-content').innerHTML=html;$('modal').showModal();}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;syncTabs();render();});document.querySelectorAll('.speed').forEach(b=>b.onclick=()=>{speed=Number(b.dataset.speed);document.querySelectorAll('.speed').forEach(x=>x.classList.toggle('active',x===b));if(playing)setPlay(true);});$('play').onclick=()=>setPlay(!playing);$('next').onclick=()=>run(()=>{F.step(state);});$('expand').onclick=()=>run(()=>F.action(state,'expand'));$('pat').onclick=()=>{toast('토토: 멍! 가현이랑 함께라서 매일 행복해 ♡');document.querySelector('.toto>span').classList.remove('wave');requestAnimationFrame(()=>document.querySelector('.toto>span').classList.add('wave'));};$('close-modal').onclick=()=>$('modal').close();$('modal').addEventListener('click',e=>{if(e.target===$('modal')){let r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('modal').close();}});
$('help').onclick=()=>openModal(`<span class="eyebrow">WELCOME TO OUR FARM</span><h2>가현이와 토토의 농장 안내</h2><p><b>가족 대항전:</b> 가족 선택에서 내 이름을 고르면 30일 도전이 시작돼요. 30일을 마치고 점수를 등록하면 가족 전체 순위표에 올라갑니다. 같은 이름의 최고점만 반영해요. 기존 자유 농장도 가족 선택에서 돌아갈 수 있어요.</p><span class="badge">하루씩 천천히</span><span class="badge">이 브라우저에 자동 저장</span><ol class="help-steps"><li><b>농장 설계:</b> 건설 탭에서 시설을 고른 뒤 빈 땅을 눌러요. 입구와 이어진 길 옆에 지어야 운영돼요. 길이 끊긴 시설에는 🔗가 표시돼요.</li><li><b>돼지 키우기:</b> 돌보기에서 아기 돼지를 맞이해요. 사료는 하루에 마리당 1kg씩 자동으로 먹어요. 충분한 사료와 건강, 길 연결이 있어야 자라요.</li><li><b>시간 보내기:</b> ‘하루 보내기’를 누르거나 ▶로 자동 진행해요. 1×는 6.5초에 하루예요. 다른 창으로 가면 자동으로 멈춰요.</li><li><b>건강 지키기:</b> 청소, 소독 시설, 토토 순찰로 방역을 높여요. 아픈 돼지는 치료해 주세요. 격리 우리는 전파·악화를 줄이고 진료소는 매일 회복을 도와요. 방역이 높아도 감염 가능성은 남아요.</li><li><b>출하와 확장:</b> 성장 8일 이상, 건강 65 이상인 아프지 않은 돼지를 출하해요. 번 돈으로 우리를 증축하고 땅을 넓혀요. 감귤 과수원은 매일 수입을 줘요.</li></ol><p>💡 처음에는 돌보기에서 토토를 순찰 보내고, 며칠 뒤 첫 출하를 해 보세요. 자금이 180 미만이면 아빠의 응원금을 최대 세 번 받을 수 있어요.</p><p>게임은 이 기기·브라우저에 저장돼요. 다른 기기로 옮겨지지 않으며 브라우저 데이터를 지우면 초기화돼요.</p>`);
$('reset').onclick=()=>openModal('<h2>새 농장을 시작할까요?</h2><p>현재 농장과 기록이 지워져요. 이 작업은 되돌릴 수 없어요.</p><button id="confirm-reset" class="primary">처음부터 다시 시작</button>');$('modal').addEventListener('click',e=>{if(e.target.id==='confirm-reset'){state=state.league?League.fresh(state.league.player):F.fresh();selected=null;tab='build';mode='pen';save();syncTabs();render();$('modal').close();toast('가현이와 토토의 새 농장이 시작됐어요.');}});document.addEventListener('visibilitychange',()=>{if(document.hidden)setPlay(false);});window.addEventListener('pagehide',save);syncTabs();render();if(loadIssue)toast('이전 저장을 읽지 못해 새 농장으로 시작했어요.');else save();
