'use strict';
const L=window.League,icons={'아빠':'👨🏻','엄마':'👩🏻','가현':'👩🏻‍🌾','지용':'👨🏻‍💼','영현':'👩🏻‍🎓'},activeKey='pig-land-active-family-v1';
let rankBusy=false,submitBusy=false,rankCache=null;
const originalRender=render,originalRun=run,originalSetPlay=setPlay;
function leagueSave(s){try{const raw=localStorage.getItem(L.key(s.league.player));if(raw){const current=JSON.parse(raw);if(current.league?.result?.finishedAt!==s.league.result?.finishedAt)return false;}localStorage.setItem(L.key(s.league.player),JSON.stringify(s));return true;}catch{return false;}}
render=function(){originalRender();let l=state.league;$('family-player').textContent=l?`${icons[l.player]} ${l.player}의 농장`:'👨‍👩‍👧‍👦 가족 선택';$('league-progress').textContent=l?`${Math.min(30,state.day-1)} / 30일 · ${l.result?'도전 완료':'가족 대항전'}`:'내 이름으로 30일 농장 대결';$('league-score').textContent=l?`🏆 ${fmt((l.result||L.score(state)).total)}점 · 순위`:'가족 순위';$('league-submit').hidden=!l?.result;$('league-submit').textContent=l?.result?.submitted?'내 결과 보기':'결과 · 점수 등록';if(l){$('day').textContent=`${Math.min(30,state.day-1)} / 30일`;$('advice').textContent=l.result?'30일 도전 완료! 가족 순위표에 기록을 남겨 보자.':$('advice').textContent;document.querySelector('.map-header h2').textContent=`${l.player}의 설계도`; }else document.querySelector('.map-header h2').textContent='가현이의 설계도';$('next').disabled=!!l?.result;$('play').disabled=!!l?.result;};
run=function(fn){if(state.league?.result){toast('30일 도전이 끝났어요. 결과를 등록하거나 새 도전을 시작해 주세요.');return;}let previousDay=state.day;originalRun(fn);if(state.league&&state.day>previousDay){let ended=L.afterDay(state);save();render();if(ended){setPlay(false);showResult();}}};
setPlay=function(on){if(on&&state.league?.result){toast('완료한 도전이에요. 새 농장을 시작해 주세요.');return;}originalSetPlay(on);};
function choosePlayer(){openModal(`<span class="eyebrow">FAMILY FARM LEAGUE</span><h2>누구의 농장으로 갈까요?</h2><p>각자 4,200코인과 돼지 4마리로 시작해요. 게임 속 30일 동안 농장을 운영하고 최고점으로 겨뤄요.</p><div class="family-choices">${L.players.map(n=>`<button data-player="${n}"><span>${icons[n]}</span><b>${n}</b></button>`).join('')}</div><p class="league-small">농장은 이 기기에서 이름별로 따로 저장됩니다. 등록한 점수만 다른 가족의 기기와 공유돼요. 이름을 선택하는 가족 놀이 방식이며 본인 인증은 하지 않아요.</p><button id="practice">기존 자유 농장으로</button>`);document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>switchPlayer(b.dataset.player));$('practice').onclick=()=>{save();let old=null;try{old=JSON.parse(localStorage.getItem(F.KEY));localStorage.removeItem(activeKey);}catch{}state=F.valid(old)?old:F.fresh();selected=null;render();$('modal').close();};}
function switchPlayer(name){save();let next=null;try{let raw=localStorage.getItem(L.key(name));if(raw){let s=JSON.parse(raw);if(L.valid(s)&&s.league.player===name)next=s;else{toast('저장된 농장을 읽지 못했어요. 기존 기록을 보존했으니 다른 이름을 선택해 주세요.');return;}}localStorage.setItem(activeKey,name);}catch{toast('저장이 제한된 브라우저예요. 창을 닫으면 농장이 사라질 수 있어요.');}state=next||L.fresh(name);selected=null;tab='build';syncTabs();save();render();$('modal').close();if(state.league.result)showResult();}
function breakdown(r){return `<dl class="score-breakdown"><div><dt>🚚 출하 실적</dt><dd>${fmt(r.sale)}</dd></div><div><dt>🪙 순자산 증가</dt><dd>${fmt(r.profit)}</dd></div><div><dt>💚 매일의 건강 관리</dt><dd>${fmt(r.care)}</dd></div><div><dt>🏅 목표 달성</dt><dd>${fmt(r.goals)}</dd></div></dl>`;}
function showResult(){let s=state,r=s.league?.result;if(!r)return;openModal(`<span class="eyebrow">30 DAYS, YOUR OWN FARM</span><h2>${s.league.player}의 30일 성적표</h2><div class="result-score">${fmt(r.total)}<small>점</small></div>${breakdown(r)}<p id="submit-message">${r.submitted?'가족 순위표에 등록한 기록이에요. 이름별 최고점이 표시됩니다.':r.pending?'아직 전송하지 못했어요. 다시 등록해 주세요.':'점수를 등록하면 가족 모두가 순위표에서 볼 수 있어요.'}</p><div class="result-actions"><button id="post-score" class="primary" ${r.submitted?'disabled':''}>${r.submitted?'등록 완료':'가족 순위에 등록'}</button><button id="result-rank">가족 순위 보기</button><button id="new-round">같은 이름으로 다시 도전</button></div>`);$('post-score').onclick=()=>submitResult(s);$('result-rank').onclick=showRank;$('new-round').onclick=()=>{openModal(`<h2>새 30일 도전을 시작할까요?</h2><p>${s.league.player}의 현재 농장이 초기화돼요. 등록된 최고점은 그대로 남아요.${r.submitted?'':' 아직 등록하지 않은 현재 점수는 사라집니다.'}</p><button id="new-round-confirm" class="primary">새 도전 시작</button>`);$('new-round-confirm').onclick=()=>{state=L.fresh(s.league.player);selected=null;save();render();$('modal').close();};};}
let apiConfig;
async function config(){if(!apiConfig)apiConfig=import('../../config.js').then(c=>({url:c.SUPABASE_URL,key:c.SUPABASE_PUBLISHABLE_KEY})).catch(e=>{apiConfig=null;throw e;});return apiConfig;}
async function api(query,body){const c=await config(),controller=new AbortController(),t=setTimeout(()=>controller.abort(),9000);try{let res=await fetch(c.url+'/rest/v1/game_scores'+query,{method:body?'POST':'GET',headers:{apikey:c.key,...(body?{'Content-Type':'application/json',Prefer:'return=minimal'}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});if(!res.ok)throw Error('rank unavailable');return body?null:await res.json();}finally{clearTimeout(t);}}
async function ranks(){return (await Promise.all(L.players.map(async name=>{let q=new URLSearchParams({select:'name,score,level',game:'eq.'+L.game,name:'eq.'+name,order:'score.desc',limit:'1'});let rows=await api('?'+q);return rows[0]||{name,score:null};}))).sort((a,b)=>(b.score??-1)-(a.score??-1));}
async function submitResult(s){if(submitBusy)return;let r=s.league.result;if(r.submitted)return;submitBusy=true;r.pending=true;leagueSave(s);let button=$('post-score');if(button){button.disabled=true;button.textContent='등록 중…';}try{let q=new URLSearchParams({select:'score',game:'eq.'+L.game,name:'eq.'+s.league.player,order:'score.desc',limit:'1'});let best=await api('?'+q);if(!best.length||best[0].score<r.total)await api('',{game:L.game,name:s.league.player,score:r.total,level:30});r.submitted=true;r.pending=false;leagueSave(s);rankCache=null;toast('가족 순위에 등록했어요. 이름별 최고점이 반영됩니다.');}catch{r.pending=true;leagueSave(s);toast('연결이 안 되어 아직 등록되지 않았어요. 점수는 이 기기에 보관했어요.');}finally{submitBusy=false;if(state===s&&$('post-score')){let b=$('post-score');b.disabled=r.submitted;b.textContent=r.submitted?'등록 완료':'다시 등록';$('submit-message').textContent=r.submitted?'가족 순위표에 등록했습니다.':'아직 온라인에 등록되지 않았어요. 연결 후 다시 등록해 주세요.';}render();}}
function rankRows(rows){let last=null,rank=0;return rows.map((r,i)=>{if(r.score!==last)rank=i+1;last=r.score;return `<tr${r.name===state.league?.player?' class="me"':''}><td>${r.score===null?'—':rank===1?'🥇':rank===2?'🥈':rank===3?'🥉':rank}</td><th scope="row">${icons[r.name]} ${r.name}</th><td>${r.score===null?'도전 전':fmt(r.score)+'점'}</td></tr>`;}).join('');}
async function showRank(){openModal('<span class="eyebrow">FAMILY LEADERBOARD</span><h2>우리 집 농장왕 🏆</h2><p id="rank-status" role="status">가족 점수를 불러오는 중…</p><table class="rank-table"><thead><tr><th>순위</th><th>가족</th><th>30일 최고점</th></tr></thead><tbody id="rank-body"></tbody></table><button id="refresh-rank">순위 새로고침</button><details class="score-rules"><summary>점수는 어떻게 계산하나요?</summary><p>출하 1마리당 100점 + 순자산 증가 10코인당 1점 + 30일 평균 건강 × 5점 + 목표 하나당 150점.</p><p>순자산은 보유 코인·사료·돼지·시설의 평가액입니다. 시작 자산, 목표 보상금, 아빠의 응원금은 수익에서 제외해요. 돼지가 없는 날은 건강 점수 0으로 계산합니다. 같은 점수는 공동 순위예요.</p></details><p class="league-small">등록한 이름별 최고점만 표시돼요. 농장 진행 상황은 기기 간에 옮겨지지 않습니다.</p>');$('refresh-rank').onclick=refreshRank;await refreshRank();}
async function refreshRank(){if(rankBusy)return;rankBusy=true;let status=$('rank-status'),body=$('rank-body'),button=$('refresh-rank');if(button)button.disabled=true;try{let rows=await ranks();rankCache=rows;if(body?.isConnected)body.innerHTML=rankRows(rows);if(status?.isConnected)status.textContent='온라인 가족 순위 · 이름별 최고점';}catch{if(status?.isConnected)status.textContent=rankCache?'연결이 끊겨 마지막으로 확인한 순위입니다.':'순위표에 연결하지 못했어요. 새로고침으로 다시 시도해 주세요.';if(body?.isConnected&&rankCache)body.innerHTML=rankRows(rankCache);}finally{rankBusy=false;if(button?.isConnected)button.disabled=false;}}
$('family-player').onclick=choosePlayer;$('league-score').onclick=showRank;$('league-submit').onclick=showResult;
try{let who=localStorage.getItem(activeKey);if(L.players.includes(who)){let raw=localStorage.getItem(L.key(who));if(raw){let s=JSON.parse(raw);if(L.valid(s)&&s.league.player===who)state=s;}}}catch{}
render();if(!state.league)choosePlayer();
